### ISSUE TITLE
Notify Driver HV Batteries Below 20% - (driver doesn't look at GLCD)

### ISSUE THREAD

**Issue by atokosch** [smit-happens/YCP_EVOS#141]
## End goal
Notify driver that the batteries are getting low. Can't use RTD sound.

Ideas:
-Slow car down if GLCD is ignored.
-Blink a light?
-Turn on and off GLCD backlight or different colors

Please Post other ideas below:

**Comment by atokosch** [comment]
If get to 15% cut down to 50% power
If get to 10% then cut the car off without the driver doing anything.

**Comment by atokosch** [comment]
related to #94

**Comment by smit-happens** [comment]
@ShawnPierpont probably based off the cell voltage average, this might be implemented in the Orion controller

**Comment by ShawnPierpont** [comment]
Implemented by setting the RPM limit very low, the driver will clearly notice this as a sign the car is low on charge

Implemented in stage manager based off of the state of charge since the state of charge seems to be more accurate at lower percentages, it seems to only act strange right after being charged, but steadies out after some discharging.
