### ISSUE TITLE
Early log message crashes serial logger.

### ISSUE THREAD

**Issue by smit-happens** [smit-happens/YCP_EVOS#160]
## Relevant Info/Links
tested this on @YoungMaker GLCD branch, wasn't working. After messing around with it, it started working
ran it on My PC and @YoungMaker both weren't working, then they both worked

### won't fix unless we see it again

**Comment by YoungMaker** [comment]
Currently, we're crashing in the onLogFiled() function in SerialLogger. The length of this message returned by `strcpy(message)` is wayy too long for the message given. A current workaround is to remove the serial logger. Possibly could be related to editing memory we're currently using/writing, editing over memory another component immediately uses (such as the SD card logger) or a race condition between two log listeners. 

For now, we will continue to use the workaround since the Serial Logger isn't of much use in the car itself.
