### ISSUE TITLE
Orion CAN messages failing

### ISSUE THREAD

**Issue by smit-happens** [smit-happens/YCP_EVOS#55]
@ShawnPierpont  add to this

**Comment by ShawnPierpont** [comment]
Look into having the BMS poll rather than polling the BMS. Then maybe we will only need to read the CAN to get the messages rather than sending a poll to the BMS for the values we need.

**Comment by smit-happens** [comment]
@ShawnPierpont please close this with resolution description

**Comment by ShawnPierpont** [comment]
After reviewing the pinout of the Teensy, I realized we were using CAN1 rather than CAN0, after modifying my code, I was able to successfully read messages off of the CAN. The BMS is also now configured to periodically send out messages that contains various details of the battery pack such as voltage, current, and state of charge that we can pick up with the Teensy. The next step is now reading only the specific messages that we are interested in, but for this issue, the communication is now set.
